exports.authRoute = require("./authRoute")
exports.webHooksRoutes = require("./webHookRoutes.js")
exports.productsRoute = require("./productsRoute.js")
exports.contactRoute = require("./contactRoute.js")
exports.orderRoute = require("./orderRoute.js")
exports.userRoutes = require("./userRoute.js")
exports.fulfillmentRoutes = require("./fulfillmentRoutes.js")

exports.productsendformRoutes = require("./productsendformRoutes.js")
exports.homedataRoutes = require("./homedataRoutes.js")
exports.pricingdataRoutes = require("./pricingdataRoutes.js")
exports.contactusdataRoutes = require("./contactusdataRoutes.js")
exports.inventorydataRoutes = require("./inventorydataRoutes.js")
exports.productdataRoutes = require("./productdataRoutes.js")
exports.contentManagementRoutes = require("./contentManagementRoutes.js")
exports.discountCodeRoutes = require("./discountCodeRoutes.js")
